org: your-organization-name
app: your-serverless-app-name
service: your-service-name
frameworkVersion: '3'
##### TODO: domain
plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

functions:
  app:
    handler: ./dist/app.handler
    events:
      - httpApi: '*'
